// <auto-generated />
namespace ConfOrganizer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Database_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Database_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201507200010236_Database_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
